%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ecar\Williams Lab Dropbox\Williams Lab Team Folder\Eric\PoxR1\NOL\POX_NOL - Sheet1.csv
%
% Auto-generated by MATLAB on 20-Apr-2026 13:28:56

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Subject", "Geno", "ProtocolNOL", "ProtocolNOR", "NOL_ENC_A_I", "NOL_ENC_B_I", "NOLENCNRatio", "NOL_ENC_A_T", "NOL_ENC_B_T", "NOLENCTRatio", "NOL_REC_A_I", "NOL_REC_B_I", "NOLRECNRatio", "NOL_REC_A_T", "NOL_REC_B_T", "NOLRECTRatio", "NOR_REC_C_I", "NOR_REC_B_I", "NORRECNRatio", "NOR_REC_C_T", "NOR_REC_B_T", "NORRECTRatio"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Subject", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Subject", "EmptyFieldRule", "auto");

% Import the data
POX_NOL_Sheet1 = readtable("C:\Users\ecar\Williams Lab Dropbox\Williams Lab Team Folder\Eric\PoxR1\NOL\POX_NOL - Sheet1.csv", opts);

clear opts
%%  Quick check


Pox_NOL_ENC_n = POX_NOL_Sheet1.NOLENCNRatio(POX_NOL_Sheet1.Geno == 1); 
CTRL_NOL_ENC_n = POX_NOL_Sheet1.NOLENCNRatio(POX_NOL_Sheet1.Geno == 0); 

Pox_NOL_ENC_t = POX_NOL_Sheet1.NOLENCTRatio(POX_NOL_Sheet1.Geno == 1); 
CTRL_NOL_ENC_t = POX_NOL_Sheet1.NOLENCTRatio(POX_NOL_Sheet1.Geno == 0);

% recall
Pox_NOL_REC_n = POX_NOL_Sheet1.NOLRECNRatio(POX_NOL_Sheet1.Geno == 1); 
CTRL_NOL_REC_n = POX_NOL_Sheet1.NOLRECNRatio(POX_NOL_Sheet1.Geno == 0); 

Pox_NOL_REC_t = POX_NOL_Sheet1.NOLRECTRatio(POX_NOL_Sheet1.Geno == 1); 
CTRL_NOL_REC_t = POX_NOL_Sheet1.NOLRECTRatio(POX_NOL_Sheet1.Geno == 0);

% NOR
Pox_NOR_REC_n = POX_NOL_Sheet1.NORRECNRatio(POX_NOL_Sheet1.Geno == 1); 
CTRL_NOR_REC_n = POX_NOL_Sheet1.NORRECNRatio(POX_NOL_Sheet1.Geno == 0); 

Pox_NOR_REC_t = POX_NOL_Sheet1.NORRECTRatio(POX_NOL_Sheet1.Geno == 1); 
CTRL_NOR_REC_t = POX_NOL_Sheet1.NORRECTRatio(POX_NOL_Sheet1.Geno == 0);

% plots

c_ord = MS_linspecer(2); 


figure(101)
clf

subplot(2,3,1)
[hb, eb, sc, p, stats] = MS_bar_w_err(CTRL_NOL_ENC_n, Pox_NOL_ENC_n, [[.3 .3 .3]; c_ord(2,:)], 1, 'ttest2', [1 2]);
 fprintf('ENC p = %0.3f   ', p)
title('Novel Object Location: Encoding')
ylabel({'Recognition index'; 'number of interactions'; "A   <-  |  ->  B"})
set(gca, 'XTickLabel', {'Tau -', 'Tau +'})
ylim([-1 1])

subplot(2,3,4)
[hb, eb, sc, p, stats] = MS_bar_w_err(CTRL_NOL_ENC_t, Pox_NOL_ENC_t, [[.3 .3 .3]; c_ord(2,:)], 1, 'ttest2', [1 2]);
ylabel({'Recognition index'; 'total interaction time'; "A   <-  |  ->  B"})
set(gca, 'XTickLabel', {'Tau -', 'Tau +'})
 fprintf('p = %0.3f\n', p)
ylim([-1 1])

subplot(2,3,2)
[hb, eb, sc, p, stats] = MS_bar_w_err(CTRL_NOL_REC_n,Pox_NOL_REC_n, [ [.3 .3 .3]; c_ord(2,:)], 1, 'ttest2', [1 2]);
title('Novel Object Location: Recall')
set(gca, 'XTickLabel', {'Tau -', 'Tau +'})
 fprintf('REC p = %0.3f   ', p)
ylim([-1 1])
ylabel({"old   <-  |  ->  new"})

subplot(2,3,5)
[hb, eb, sc, p, stats] = MS_bar_w_err(CTRL_NOL_REC_t,Pox_NOL_REC_t, [ [.3 .3 .3]; c_ord(2,:)], 1, 'ttest2', [1 2]);
set(gca, 'XTickLabel', {'Tau -', 'Tau +'})
 fprintf('p = %0.3f\n', p)
ylabel({"old   <-  |  ->  new"})
ylim([-1 1])

subplot(2,3,3)
[hb, eb, sc, p, stats] = MS_bar_w_err(CTRL_NOR_REC_n,Pox_NOR_REC_n, [ [.3 .3 .3]; c_ord(2,:)], 1, 'ttest2', [1 2]);
title('Novel Object Recog: Recall')
set(gca, 'XTickLabel', {'Tau -', 'Tau +'})
 fprintf('NOR p = %0.3f   ', p)
ylim([-1 1])
ylabel({"old   <-  |  ->  new"})

subplot(2,3,6)
[hb, eb, sc, p, stats] = MS_bar_w_err(CTRL_NOR_REC_t,Pox_NOR_REC_t, [ [.3 .3 .3]; c_ord(2,:)], 1, 'ttest2', [1 2]);
set(gca, 'XTickLabel', {'Tau -', 'Tau +'})
 fprintf('p = %0.3f\n', p)
ylim([-1 1])
ylabel({"old   <-  |  ->  new"})


 saveas(gcf, "C:\Users\ecar\Williams Lab Dropbox\Williams Lab Team Folder\Eric\PoxR1\NOL\NOL_summary.fig")